### ISSUE TITLE
React 19 and react.dev

### ISSUE THREAD

**Issue by eps1lon** [eps1lon/DefinitelyTyped#22]
Test types on https://github.com/reactjs/react.dev including codemod.

**Comment by eps1lon** [comment]
Conclusion: https://github.com/eps1lon/reactjs.org/pull/1#issuecomment-2011912784

**Comment by Fun32secg32** [comment]
> [Codemod dahil olmak üzere https://github.com/reactjs/react.dev](https://github.com/reactjs/react.dev) adresindeki test türleri .
